apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: main  # Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      nodeSelector:
        disktype: ssd 
      containers:
        - name: flask-app
          image: ranaessam/library-management-system_backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
      #     volumeMounts:
      #       - mountPath: /app  # Adjust to match the path inside the container
      #         name: flask-app-volume
      #         subPath: Database.json
      # # volumes:
      #   - name: flask-app-volume
      #     persistentVolumeClaim:
      #       claimName: json-pvc