apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort  # Exposes the service on each node's IP at a static port
  ports:
    - port: 80       # Port exposed on the service
      targetPort: 5000  # Port on the container (Flask app)
      nodePort: 30000   # A different NodePort accessible on each Kubernetes node
  selector:
    app: flask-app  # Must match the labels in your Deployment
    
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   # namespace: librarymanagementsystem
# spec:
#   selector:
#     app: library-system
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 5000
#   type: LoadBalancer
  
