apiVersion:  client.authentication.k8s.io/v1
kind: Deployment
metadata:
  name: frontend-deployment
  # namespace: librarymanagementsystem
  labels:
    app: library-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-system
  template:
    metadata:
      labels:
        app: library-system
    spec:
      containers:
        - name: frontend
          image: ranaessam/library-management-system_frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: NODE_ENV
              value: "development"
              
