apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: librarymanagementsystem
spec:
  selector:
    app: library-system
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
