apiVersion:  client.authentication.k8s.io/v1
kind: Service
metadata:
  name: frontend-service
  # namespace: librarymanagementsystem
spec:
  selector:
    app: library-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: LoadBalancer
  
